{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "conductor",
        "Service": "/GTAProyect/Services/MobilGTA.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "documento": "#Control:documento/#Value",
        "nombre": "#Control:nombre/#Value",
        "apellido": "#Control:apellido/#Value",
        "telefono": "#Control:telefono/#Value",
        "email": "#Control:email/#Value",
        "direccion": "#Control:direccion/#Value",
        "observacion": "#Control:observacion/#Value",
        "ciudad": "#Control:ciudad/#Value",
        "status": "#Control:status/#Value",
        "placa_placa": "#Control:placa_placa/#SelectedValue"
    },
    "UpdateLinks": [],
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": "/GTAProyect/Actions/UpdateEntitySuccessMessage.action",
    "OnFailure": "/GTAProyect/Actions/UpdateEntityFailureMessage.action"
}