{
	"_Type": "Action.Type.ODataService.CreateRelatedEntity",
	"ActionResult": {
		"_Name": "create"
	},
	"OnFailure": "/GTAProyect/Actions/CreateEntityFailureMessage.action",
	"OnSuccess": "/GTAProyect/Actions/CreateEntitySuccessMessage.action",
	"Target": {
		"Service": "/GTAProyect/Services/MobilGTA.service",
		"EntitySet": "fallas"
	},
	"ParentLink": {
		"Target": {
			"EntitySet": "maquinaria",
			"ReadLink": "{@odata.readLink}"
		},
		"Property": "fallas"
	},
	"Properties": {
		"ID": "#Control:ID/#Value",
		"fecha": "#Control:fecha/#Value",
		"cabina": "#Control:cabina/#SelectedValue",
		"motor": "#Control:motor/#SelectedValue",
		"pluma": "#Control:pluma/#SelectedValue",
		"brazo": "#Control:brazo/#SelectedValue",
		"cucharon": "#Control:cucharon/#SelectedValue",
		"estabilizador": "#Control:estabilizador/#SelectedValue",
		"cilindro": "#Control:cilindro/#SelectedValue",
		"status": "#Control:status/#Value",
		"maquinaria_ID": "#Control:maquinaria_ID/#SelectedValue"
	}
}