{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "update"
	},
	"OnFailure": "/GTAProyect/Actions/UpdateEntityFailureMessage.action",
	"OnSuccess": "/GTAProyect/Actions/UpdateEntitySuccessMessage.action",
	"Target": {
		"EntitySet": "actividades",
		"Service": "/GTAProyect/Services/MobilGTA.service",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties": {
		"ID": "#Control:ID/#Value",
		"tipo": "#Control:tipo/#Value",
		"hora_inicio": "#Control:hora_inicio/#Value",
		"hora_fin": "#Control:hora_fin/#Value",
		"sitio_cargue": "#Control:sitio_cargue/#Value",
		"sitio_descargue": "#Control:sitio_descargue/#Value",
		"vale_interno": "#Control:vale_interno/#Value",
		"vale_proovedor": "#Control:vale_proovedor/#Value",
		"peaje": "#Control:peaje/#Value",
		"status": "#Control:status/#Value"
	}
}