{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "update"
	},
	"OnFailure": "/GTAProyect/Actions/UpdateEntityFailureMessage.action",
	"OnSuccess": "/GTAProyect/Actions/UpdateEntitySuccessMessage.action",
	"Target": {
		"EntitySet": "motor",
		"Service": "/GTAProyect/Services/MobilGTA.service",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties": {
		"ID": "#Control:ID/#Value",
		"fuga_aceite": "#Control:fuga_aceite/#SelectedValue",
		"ruido_motor": "#Control:ruido_motor/#SelectedValue",
		"desajuste": "#Control:desajuste/#SelectedValue",
		"exeso_humo": "#Control:exeso_humo/#SelectedValue",
		"dano": "#Control:dano/#Value",
		"causa": "#Control:causa/#Value",
		"status": "#Control:status/#Value",
		"placa_placa": "#Control:placa_placa/#SelectedValue"
	}
}