{
    "CreateLinks": [],
    "OnFailure": "/GTAProyect/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/GTAProyect/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "ID": "#Control:ID/#Value",
        "fecha": "#Control:fecha/#Value",
        "hora": "#Control:hora/#Value",
        "kilometraje": "#Control:kilometraje/#Value",
        "observaciones": "#Control:observaciones/#Value",
        "adjunto": "#Control:adjunto/#Value",
        "status": "#Control:status/#Value"
    },
    "Target": {
        "EntitySet": "registro_maquinaria",
        "Service": "/GTAProyect/Services/MobilGTA.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateEntity"
}